import mongoose from 'mongoose';

async function run() {
    await mongoose.connect('mongodb+srv://exim:I9y5bcMUHkGHpgq2@exim.xya3qh0.mongodb.net/export');
    console.log("Connected to MongoDB Production");

    const db = mongoose.connection.collection('exportjobs');

    // 1. Find jobs that do not have /SEA/ or /AIR/ in their job_no
    // This will match AMD/00149/25-26 but NOT AMD/SEA/00149/25-26
    const wrongJobs = await db.find({
        job_no: { $not: /\/(SEA|AIR)\//i }
    }).toArray();

    console.log(`Found ${wrongJobs.length} jobs without /SEA/ or /AIR/ in the job number.`);

    let updatedCount = 0;
    let deletedCount = 0;
    let errorCount = 0;

    for (const job of wrongJobs) {
        if (!job.job_no) continue;

        // Determine what mode it should be
        let mode = 'SEA'; // Default
        if (job.transportMode && String(job.transportMode).toUpperCase() === 'AIR') {
            mode = 'AIR';
        } else if (job.consignmentType && String(job.consignmentType).toUpperCase() === 'AIR') {
            mode = 'AIR';
        }

        // Attempt to convert to new format, e.g. AMD/00149/25-26 -> AMD/SEA/00149/25-26
        const parts = job.job_no.split('/');
        let targetJobNo = job.job_no;

        // Look for the sequence string (the numeric part like 00149)
        const seqIndex = parts.findIndex(p => /^\d{3,}$/.test(p));

        if (seqIndex > 0) {
            const newParts = [...parts];
            newParts.splice(seqIndex, 0, mode);
            targetJobNo = newParts.join('/');
        } else if (parts.length >= 2) {
            const newParts = [...parts];
            newParts.splice(1, 0, mode);
            targetJobNo = newParts.join('/');
        }

        if (targetJobNo !== job.job_no) {
            // Check if the target (correct) format already exists
            const exists = await db.findOne({ job_no: { $regex: `^${targetJobNo}$`, $options: "i" } });

            if (exists) {
                // Target exists - this is a duplicate generated by legacy bad data. Delete the old bad one.
                try {
                    await db.deleteOne({ _id: job._id });
                    deletedCount++;
                    console.log(`DELETED duplicate legacy job: ${job.job_no} (Correct ${targetJobNo} already exists)`);
                } catch (err) {
                    errorCount++;
                    console.error(`Failed to delete legacy job ${job.job_no}:`, err.message);
                }
            } else {
                // Target DOES NOT exist - this is a genuine job that was just named wrong. Rename it.
                try {
                    // Update the job_no and jobNumber fields
                    await db.updateOne(
                        { _id: job._id },
                        { $set: { job_no: targetJobNo, jobNumber: targetJobNo, transportMode: mode } }
                    );
                    updatedCount++;
                    console.log(`CONVERTED: ${job.job_no} -> ${targetJobNo}`);
                } catch (err) {
                    errorCount++;
                    console.error(`Failed to convert job ${job.job_no}:`, err.message);
                }
            }
        } else {
            console.log(`SKIPPING (could not parse): ${job.job_no}`);
        }
    }

    console.log("\n--- RESULT ---");
    console.log(`Converted to SEA/AIR: ${updatedCount}`);
    console.log(`Deleted as duplicates: ${deletedCount}`);
    console.log(`Errors: ${errorCount}`);

    // 2. Sync Sequences Logic
    const validJobs = await db.find({}).toArray();
    const maxSeqs = {};

    for (let j of validJobs) {
        if (!j.job_no) continue;
        const parts = j.job_no.split('/');
        if (parts.length >= 3) {
            const branchLower = parts[0].toUpperCase();
            let mode = 'SEA';
            let year = j.year;

            let seqStr = parts[1];
            if (parts[1].toUpperCase() === 'AIR' || parts[1].toUpperCase() === 'SEA') {
                mode = parts[1].toUpperCase();
                seqStr = parts[2];
                if (parts.length > 3) {
                    year = parts[3] || j.year;
                }
            } else if (j.job_no.toUpperCase().includes('/AIR/')) {
                mode = 'AIR';
            }

            if (!year) year = j.year;

            if (/^\d+$/.test(seqStr)) {
                const seq = parseInt(seqStr, 10);
                if (!['AMD', 'BRD', 'GIM', 'COK', 'HAZ'].includes(branchLower)) {
                    continue;
                }
                const branchKey = `${branchLower}-${mode}`;
                const key = `${branchKey}|${year}`;

                if (!maxSeqs[key] || seq > maxSeqs[key]) {
                    maxSeqs[key] = seq;
                }
            }
        }
    }

    console.log("\nMax seqs from valid jobs:", maxSeqs);

    for (const [key, maxSeq] of Object.entries(maxSeqs)) {
        const [branch, year] = key.split('|');
        console.log(`Setting ${branch} ${year} to ${maxSeq}`);
        await mongoose.connection.collection('jobsequences').updateOne(
            { branch: branch, year: year },
            { $set: { lastSequence: maxSeq } },
            { upsert: true }
        );
    }

    console.log("Sequences synced.");
    process.exit();
}

run().catch(console.error);
