// commonStyles.js (or keep inline)
export const styles = {
  page: {
    fontFamily: "'Segoe UI', Roboto, Arial, sans-serif",
    fontSize: 13,
    color: "#1e2e38",
    padding: 16,
  },
  sectionTitle: {
    fontWeight: 700,
    color: "#16408f",
    fontSize: 12,
    marginBottom: 10,
    letterSpacing: 1.3,
    textTransform: "uppercase",
  },
  subSectionTitle: {
    fontWeight: 700,
    color: "#16408f",
    fontSize: 11,
    marginTop: 12,
    marginBottom: 8,
    borderBottom: "1px solid #e2e8f0",
    paddingBottom: 4,
  },
  card: {
    background: "#fff",
    border: "1.5px solid #e2e8f0",
    borderRadius: 7,
    padding: 16,
    marginBottom: 18,
  },
  cardTitle: {
    fontWeight: 700,
    color: "#16408f",
    fontSize: 14,
    marginBottom: 12,
  },
  grid4: {
    display: "grid",
    gridTemplateColumns: "repeat(4, minmax(0, 1fr))",
    gap: 16,
    marginBottom: 8,
    alignItems: "end",
  },
  grid3: {
    display: "grid",
    gridTemplateColumns: "repeat(3, minmax(0, 1fr))",
    gap: 16,
    marginBottom: 8,
    alignItems: "end",
  },
  grid2: {
    display: "grid",
    gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
    gap: 16,
    marginBottom: 8,
    alignItems: "end",
  },
  field: { marginBottom: 8 },
  label: {
    fontSize: 11,
    fontWeight: 700,
    color: "#263046",
    letterSpacing: 0.5,
    marginBottom: 4,
    display: "block",
  },
  input: {
    width: "100%",
    fontSize: 12,
    padding: "4px 8px",
    border: "1px solid #bdc7d1",
    borderRadius: 3,
    height: 28,
    background: "#f7fafc",
    outline: "none",
    boxSizing: "border-box",
  },
  textarea: {
    width: "100%",
    fontSize: 12,
    padding: "5px 8px",
    border: "1.5px solid #ccd6dd",
    borderRadius: 4,
    minHeight: 45,
    background: "#f7fafc",
    resize: "vertical",
    boxSizing: "border-box",
  },
  select: {
    width: "100%",
    fontSize: 12,
    padding: "4px 8px",
    border: "1px solid #bdc7d1",
    borderRadius: 3,
    height: 28,
    background: "#f7fafc",
    outline: "none",
    boxSizing: "border-box",
    cursor: "pointer",
  },
  checkboxRow: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    fontSize: 11,
    fontWeight: 700,
    color: "#263046",
    textTransform: "uppercase",
    marginBottom: 8,
  },
  tableHeaderRow: {
    display: "grid",
    gridTemplateColumns: "0.7fr 1.3fr 1fr 1.1fr 0.9fr 1.1fr 1.2fr 0.6fr",
    gap: 8,
    fontSize: 11,
    fontWeight: 700,
    color: "#f7fafc",
    background: "#16408f",
    padding: "6px 10px",
    marginTop: 8,
  },
  tableRow: {
    display: "grid",
    gridTemplateColumns: "0.7fr 1.3fr 1fr 1.1fr 0.9fr 1.1fr 1.2fr 0.6fr",
    gap: 8,
    padding: "6px 10px",
    alignItems: "center",
    borderBottom: "1px solid #e2e8f0",
  },
  tableContainer: {
    border: "1.5px solid #e2e8f0",
    borderRadius: 7,
    background: "#fff",
    marginBottom: 12,
    maxHeight: 320,
    overflow: "auto",
  },
  smallButton: {
    padding: "4px 10px",
    fontSize: 11,
    borderRadius: 4,
    border: "1px solid #16408f",
    background: "#16408f",
    color: "#fff",
    cursor: "pointer",
    fontWeight: 600,
  },
  linkButton: {
    padding: "3px 8px",
    fontSize: 11,
    borderRadius: 4,
    border: "1px solid #e53e3e",
    background: "#fff5f5",
    color: "#e53e3e",
    cursor: "pointer",
    fontWeight: 600,
  },
};
